// e2e/content-studio-screenshots.spec.ts
// OPTIONAL evidence artifacts — Podcast Slice 4, section 40.
//
// These screenshots are UNINSPECTED Human-review artifacts stored OUTSIDE
// the repository (/tmp/opencode/fep-content-studio/). They are generated
// for a human reviewer and are NOT proof of anything; the automated
// contracts live in content-studio.spec.ts and the smoke suites.
//
// Opt-in like the other evidence specs: run with FEP_SCREENSHOTS=1 to
// generate the artifacts (CI and the default `pnpm test:e2e:full` skip it,
// so evidence capture never adds mandatory release-gate runtime).

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { ADMIN_URL } from '../playwright.config';
import { buildStoreZip, packageDirToZipEntries } from '../scripts/content/fixtures.mjs';
import { createStaff, PB_URL, superuserAuth } from './fixtures';

const OUT = '/tmp/opencode/fep-content-studio';
const EXAMPLE_DIR = join(process.cwd(), 'content-packages', 'example-episode');

let staff: Awaited<ReturnType<typeof createStaff>>;
let episodeId = '';
let zipPath = '';

test.beforeAll(async () => {
  const su = await superuserAuth();
  staff = await createStaff(su);
  mkdirSync(OUT, { recursive: true });

  // Reusable store-method ZIP from the committed example package.
  const manifest = JSON.parse(readFileSync(join(EXAMPLE_DIR, 'episode.json'), 'utf8')) as {
    episode: { slug: string };
  };
  const zipDir = join('/tmp', `fep-shots-${Date.now().toString(36)}`);
  mkdirSync(zipDir, { recursive: true });
  zipPath = join(zipDir, 'example-episode.zip');
  writeFileSync(zipPath, buildStoreZip(packageDirToZipEntries(EXAMPLE_DIR, manifest)));
  writeFileSync(
    join(OUT, 'README.txt'),
    'UNINSPECTED Human-review artifacts — generated by e2e/content-studio-screenshots.spec.ts. Not proof of behavior.\n',
  );

  // Seed: publish a category, a draft episode with artwork + a complete B1
  // variant (summary, audio, transcript, vocabulary), plus an import audit.
  const cats = await fetch(`${PB_URL}/api/fast-english/staff/categories`, {
    headers: { authorization: staff.token },
  });
  const general = ((await cats.json()) as { items: Array<{ id: string }> }).items[0];

  const epRes = await fetch(`${PB_URL}/api/fast-english/staff/episodes`, {
    method: 'POST',
    headers: { authorization: staff.token, 'content-type': 'application/json' },
    body: JSON.stringify({
      title_fa: 'اهرام مصر',
      title: 'Pyramids of Egypt',
      slug: `shots-${Date.now().toString(36)}`,
      description_fa: 'روایت تاریخی درباره معماری و تاریخچه اهرام مصر برای دانشجویان سطوح مختلف.',
      category: general.id,
      episode_number: 3,
    }),
  });
  episodeId = ((await epRes.json()) as { episode: { id: string } }).episode.id;

  const square = readFileSync(join(EXAMPLE_DIR, 'artwork', 'square.png'));
  const upload = await fetch(`${PB_URL}/api/fast-english/staff/episodes/${episodeId}/artwork`, {
    method: 'POST',
    headers: { authorization: staff.token },
    body: (() => {
      const fd = new FormData();
      fd.append('media', new Blob([square], { type: 'image/png' }), 'square.png');
      return fd;
    })(),
  });
  expect(upload.status).toBe(200);

  const vRes = await fetch(`${PB_URL}/api/fast-english/staff/episodes/${episodeId}/variants`, {
    method: 'POST',
    headers: { authorization: staff.token, 'content-type': 'application/json' },
    body: JSON.stringify({ level: 'B1' }),
  });
  const variantId = ((await vRes.json()) as { variant: { id: string } }).variant.id;

  const mp3 = readFileSync(join(EXAMPLE_DIR, 'audio', 'b1.mp3'));
  const audioUp = await fetch(`${PB_URL}/api/fast-english/staff/variants/${variantId}/audio`, {
    method: 'POST',
    headers: { authorization: staff.token },
    body: (() => {
      const fd = new FormData();
      fd.append('audio', new Blob([mp3], { type: 'audio/mpeg' }), 'b1.mp3');
      return fd;
    })(),
  });
  expect(audioUp.status).toBe(200);

  await fetch(`${PB_URL}/api/fast-english/staff/variants/${variantId}`, {
    method: 'PATCH',
    headers: { authorization: staff.token, 'content-type': 'application/json' },
    body: JSON.stringify({ summary_fa: 'خلاصه فارسی نسخه B1 درباره اهرام مصر.' }),
  });
  await fetch(`${PB_URL}/api/fast-english/staff/variants/${variantId}/transcript`, {
    method: 'PUT',
    headers: { authorization: staff.token, 'content-type': 'application/json' },
    body: JSON.stringify({
      transcript:
        '# The Pyramids of Egypt\n\nThis episode explores the history and architecture of the pyramids with clear, simple language for learners.\n\nThe builders moved enormous stone blocks into place over many years.',
    }),
  });
  await fetch(`${PB_URL}/api/fast-english/staff/variants/${variantId}/vocabulary`, {
    method: 'POST',
    headers: { authorization: staff.token, 'content-type': 'application/json' },
    body: JSON.stringify({
      term: 'pyramid',
      meaning_fa: 'هرم',
      definition_en: 'A large stone structure.',
    }),
  });
});

async function auth(page: import('@playwright/test').Page, path: string) {
  await page.goto(`${ADMIN_URL}/login`);
  await page.evaluate(
    ({ t, r }) => localStorage.setItem('fep_staff_auth', JSON.stringify({ token: t, model: r })),
    { t: staff.token, r: staff.record },
  );
  await page.goto(`${ADMIN_URL}${path}`, { waitUntil: 'domcontentloaded' });
}

const VIEWPORTS = [
  { width: 390, height: 844 },
  { width: 768, height: 1024 },
  { width: 1440, height: 900 },
];

const ENV_FLAG = process.env.FEP_SCREENSHOTS === '1';

test('generate uninspected content-studio screenshots', async ({ page }) => {
  test.skip(!ENV_FLAG, 'opt-in: set FEP_SCREENSHOTS=1 to generate human-review artifacts');
  const shots: Array<{ path: string; setup: () => Promise<void> }> = [
    { path: '01-content-overview', setup: async () => auth(page, '/content') },
    { path: '02-episode-list', setup: async () => auth(page, '/content/episodes') },
    { path: '03-episode-editor', setup: async () => auth(page, `/content/episodes/${episodeId}`) },
    {
      path: '04-level-matrix',
      setup: async () => {
        await auth(page, `/content/episodes/${episodeId}`);
        await expect(page.getByTestId('episode-tabs')).toBeVisible();
        await page.getByTestId('episode-tab-levels').click();
      },
    },
    {
      path: '05-variant-editor',
      setup: async () => auth(page, `/content/episodes/${episodeId}/variants/B1`),
    },
    {
      path: '06-vocabulary-editor',
      setup: async () => {
        await auth(page, `/content/episodes/${episodeId}/variants/B1`);
        await page.getByTestId('vocab-batch-toggle').click();
      },
    },
    { path: '07-import-validation', setup: async () => auth(page, '/content/import') },
    {
      path: '08-import-plan',
      setup: async () => {
        await auth(page, '/content/import');
        await page.getByTestId('import-input').setInputFiles(zipPath);
        await expect(page.getByTestId('import-report-status')).toContainText('معتبر');
        await page.getByTestId('import-to-plan').click();
      },
    },
    {
      path: '09-preview',
      setup: async () => auth(page, `/content/preview/${episodeId}`),
    },
    {
      path: '10-readiness',
      setup: async () => {
        await auth(page, `/content/episodes/${episodeId}/variants/B1`);
      },
    },
  ];

  for (const shot of shots) {
    for (const vp of VIEWPORTS) {
      await page.setViewportSize(vp);
      await shot.setup();
      await page.waitForTimeout(900);
      await page.screenshot({
        path: join(OUT, `${shot.path}-${vp.width}x${vp.height}-light.png`),
        fullPage: false,
      });
    }
  }

  // Dark scheme spot-checks on the two most useful screens.
  await page.setViewportSize({ width: 1440, height: 900 });
  await auth(page, '/settings');
  await page.getByTestId('admin-theme-switch').locator('[data-value="dark"]').click();
  await page.waitForTimeout(500);
  await auth(page, `/content/episodes/${episodeId}`);
  await page.waitForTimeout(900);
  await page.screenshot({ path: join(OUT, '03-episode-editor-1440x900-dark.png') });
  await auth(page, '/content');
  await page.waitForTimeout(900);
  await page.screenshot({ path: join(OUT, '01-content-overview-1440x900-dark.png') });

  expect(true).toBe(true);
});
