// shared/content-package/constants.ts
// Podcast Slice 3 — stable constants for the Episode Content Package
// pipeline: specification version, asset limits aligned with the Slice 2
// database contract (docs/PODCAST_DOMAIN.md), and documented editorial
// thresholds. Both the CLI pipeline and the future Admin Console use
// these values; the PocketBase hooks re-implement the same limits
// (server-side validation is always authoritative).

/** Manifest specification version supported by this pipeline. */
export const PACKAGE_SCHEMA_VERSION = '1.0.0';

/** Default CEFR level generated by the template generator. */
export const TEMPLATE_DEFAULT_LEVEL = 'B1';

// --- Asset limits (mirror the PocketBase field contract) ---

/** artwork_square / hero_image_wide / thumbnail_override: 5 MB. */
export const ARTWORK_MAX_BYTES = 5 * 1024 * 1024;

/** lessons.audio: 10 MB (MP3/M4A only for imported packages). */
export const AUDIO_MAX_BYTES = 10 * 1024 * 1024;

/** lesson_vocabulary.pronunciation_audio: 2 MB (MP3/M4A). */
export const PRONUNCIATION_MAX_BYTES = 2 * 1024 * 1024;

/** lessons.body (transcript): 50 000 chars (field max). */
export const TRANSCRIPT_MAX_CHARS = 50_000;

/** Maximum transcript file size read from disk (UTF-8 text). */
export const TRANSCRIPT_MAX_BYTES = 256 * 1024;

/** Imported audio formats supported by the pipeline. */
export const AUDIO_MIME_TYPES = ['audio/mpeg', 'audio/mp4'] as const;

/** Pronunciation formats (lesson_vocabulary.pronunciation_audio). */
export const PRONUNCIATION_MIME_TYPES = ['audio/mpeg', 'audio/mp4'] as const;

/** Imported artwork formats (topics artwork fields). */
export const ARTWORK_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp'] as const;

// --- Artwork geometry policy ---

/** Square tolerance: |width - height| <= this many pixels. */
export const ARTWORK_SQUARE_TOLERANCE_PX = 8;

/** Recommended minimum square artwork dimension. */
export const ARTWORK_MIN_DIMENSION_PX = 512;

/** Hero must be landscape: height <= width. */
export const HERO_LANDSCAPE_MIN_RATIO = 1.0;

/** Hero ratio warning window around 16:9 (1.777). */
export const HERO_RATIO_LOW = 1.4;
export const HERO_RATIO_HIGH = 2.1;

// --- Editorial copy thresholds (documented in docs/CONTENT_PIPELINE.md) ---

/** Warning when the Persian title exceeds this many characters. */
export const TITLE_FA_MAX_WARN = 60;

/** Warning when the English title exceeds this many characters. */
export const TITLE_EN_MAX_WARN = 60;

/** Warning when the Persian description is shorter than this. */
export const DESCRIPTION_FA_MIN_WARN = 40;

/** Warning when a transcript is shorter than this many characters. */
export const TRANSCRIPT_MIN_CHARS_WARN = 1_000;

/** Warning when a word is repeated more than this many times in a title. */
export const TITLE_WORD_REPEAT_MAX = 2;

/** Warning when a variant declares more vocabulary entries than this. */
export const VOCABULARY_COUNT_HIGH_WARN = 20;

/**
 * Placeholder patterns that block an import until real editorial copy is
 * provided. The template generator emits TODO_REPLACE values that are
 * deliberately rejected by validation.
 */
export const PLACEHOLDER_PATTERNS: readonly RegExp[] = [
  /TODO_REPLACE/i,
  /\bTBD\b/i,
  /\bFIXME\b/i,
  /\bPLACEHOLDER\b/i,
  /lorem ipsum/i,
  /«به‌زودی»/,
  /\bXXX\b/i,
];

/**
 * Generic artwork alt values that trigger a warning (never a block).
 */
export const GENERIC_ART_ALT_PATTERNS: readonly RegExp[] = [
  /^(art|artwork|image|cover|تصویر|عکس|آرت‌ورک|جلد)$/i,
];

/** Transcript constructs that are rejected (blocking). */
export const TRANSCRIPT_FORBIDDEN_PATTERNS: readonly { code: string; pattern: RegExp }[] = [
  { code: 'TRANSCRIPT_EMBEDDED_SCRIPT', pattern: /<script[\s>]/i },
  { code: 'TRANSCRIPT_EMBEDDED_SCRIPT', pattern: /<iframe[\s>]/i },
  { code: 'TRANSCRIPT_EMBEDDED_SCRIPT', pattern: /<object[\s>]/i },
  { code: 'TRANSCRIPT_EMBEDDED_SCRIPT', pattern: /<embed[\s>]/i },
  { code: 'TRANSCRIPT_UNSAFE_LINK', pattern: /javascript:/i },
];

// --- Package path safety ---

/** Package-relative asset path rule (shared with the server hooks). */
export const ASSET_PATH_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;

/**
 * Checks a package-relative asset path for structural dangers:
 * traversal segments, absolute paths, Windows/UNC paths, backslashes,
 * null bytes and encoded traversal. The CLI additionally compares real
 * resolved paths against the real package root (symlink escape).
 */
export function isUnsafeAssetPath(path: string): boolean {
  if (typeof path !== 'string' || path.length === 0 || path.length > 200) return true;
  if (path.includes('\u0000')) return true;
  if (path.includes('\\')) return true;
  if (path.startsWith('/')) return true;
  if (/^[A-Za-z]:/.test(path)) return true;
  if (path.startsWith('//') || path.startsWith('\\\\')) return true;
  if (path.includes('%2e%2e') || path.includes('%2E%2E')) return true;
  const segments = path.split('/');
  for (const seg of segments) {
    if (seg === '..' || seg === '.' || seg === '') return true;
  }
  return !ASSET_PATH_PATTERN.test(path);
}
